### ISSUE TITLE
Icons appear corrupted in WSL with Ubuntu 22.04.3 LTS

### ISSUE THREAD

**Issue by nikosandreou** [shiftkey/desktop#1009]
### The problem

I am using Github-Desktop for Linux on my corporate laptop through WSL. The host OS is Windows 11 and the WSL info is this:

> 
> WSL version: 2.0.14.0
> Kernel version: 5.15.133.1-1
> WSLg version: 1.0.59
> MSRDC version: 1.2.4677
> Direct3D version: 1.611.1-81528511
> DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
> Windows version: 10.0.22631.3007

Up until yesterday, the program was working fine. Late in the evening, I was prompted to install new Intel Graphics Drivers, specifically 31.0.101.4953. This is controlled by the company through Dell Command | Update. Didn't check anything after the install but today, I noticed that Github Desktop icons appear corrupted. You can see the attached images. IntelliJ and Firefox, Sublime text as well as other Ubuntu components appear to not have any issues.

Not sure what else to do check or if it is a known issue.

### Release version

3.3.8-linux1

### Operating system

Ubuntu 22.04.3 LTS (through WSLg)

### Steps to reproduce the behavior

Just open the app and check the icons. I open the app either through terminal or the start menu in Windows and the result is the same.

Tried wsl --shutdown and to start it again, same result.

Tried restart of the host OS, the same result.

### Screenshots

![image](https://github.com/shiftkey/desktop/assets/152171018/652eb026-53ee-4ce8-b1ec-9caf0b486bce)
![image](https://github.com/shiftkey/desktop/assets/152171018/3df43ec4-a62e-42dc-acac-78bec300f32f)
![image](https://github.com/shiftkey/desktop/assets/152171018/695c8512-6815-429e-84a1-a9eca751506d)

**Comment by shiftkey** [comment]
> 3.3.8-linux1

Not sure what to link this to, but this version is Electron v26, and I've published `3.3.12-linux2` which should be a stable Electron v28. I would advise re-testing with this version and seeing if this behaviour changes at all.

**Comment by nikosandreou** [comment]
Hi Brendan. I did try the latest version, the icons appear the same as the screenshots. :( Not sure what broke this. Since this is a business laptop, I cannot control updates to try previous gfx driver version. I will try my best to troubleshoot.

**Comment by nikosandreou** [comment]
@shiftkey I downgraded the driver to my Dell Latitude 7440 from:

Intel-UHD-Graphics-Driver_7X9T5_WIN64_31.0.101.4953_A06.EXE

to:

Intel-UHD-Graphics-Driver_R0F3F_WIN64_31.0.101.4824_A05.EXE

The icons are back to normal. Can't say what affects this but this is awkward. Running Github-Desktop natively in Windows, runs without issues with latest driver (4953). Running in WSLg with latest driver (4953), icons appear corrupted.

With previous driver (4824), both work fine. This is a tricky one... Other Electron apps work fine with latest driver (4953).

**Comment by nikosandreou** [comment]
@shiftkey 

Retested with new driver, version 31.0.101.5333, A07 (Intel-UHD-Graphics-Driver_G52T6_WIN64_31.0.101.5333_A07.EXE)

and docker-desktop version 3.4.2-linux1.

Unfortunately, the issue persists. Same icon corruption. :( Latest driver version is critical one and it is enforced through group policy in my business laptop even if I rollback to previous driver version.
