### ISSUE TITLE
The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed. getting this error even through everything is correct 

### ISSUE THREAD

**Issue by rishabhatishae** [shiftkey/desktop#946]

**Comment by rishabhatishae** [comment]
getting this error on pull and push i'm able to commit and for push pull it is working on terminal

**Comment by HomeworldL** [comment]
I'm having the same problem. It just appeared recently

**Comment by rishabhatishae** [comment]
so it is resolved  ??

**Comment by gugajazz** [comment]
Getting the same issue. Tried to uninstall and then install the latest version and now it wont start.

**Comment by rishabhatishae** [comment]
okay

**Comment by andygeorge** [comment]
Possible duplicate of https://github.com/shiftkey/desktop/issues/942

**Comment by ucihariskoding** [comment]
```
> dell7300@localhost:~> sudo zypper in github-desktop
Loading repository data...
Reading installed packages...
'github-desktop' not found in package names. Trying capabilities.
No provider of 'github-desktop' found.
Resolving package dependencies...
Nothing to do.
dell7300@localhost:~> 
```
i am using opensuse tumbleweed ( slowroll) and have used 2 repos from shiftkey and mwt packages but the app still doesnt exist

**Comment by shiftkey** [comment]
I need more details from the application to be able to troubleshoot further. Please check the logs created at `~/.config/GitHub\ Desktop/logs/` from around the time of the issue to see if there's any helpful messages that might explain the underlying behaviour.

**Comment by Vexthecollector** [comment]
Got the same error. Found the actual error though. Which is that OAuth is required to use the repository. 
So that is why I can't use it with Github desktop currently. Good to know.

**Comment by Vexthecollector** [comment]
It's not really completed?
The error, at least in part, seems to be related to OAuth issues.
